### ISSUE TITLE
Document how to specify the SSH-KEY pub on the UI

### ISSUE THREAD

**Issue by afiune** [chef-boneyard/delivery_self_guided_trial#15]
As a user I would expect to have documentation about how to set my SSH-KEY public key through the UI  so I don't have to guess or learn by my own where to do that in Delivery.

**Comment by afiune** [comment]
For reference, the only place we say something about the pub key is at https://github.com/chef/delivery_self_guided_trial/blob/master/workstation_setup.md#log-in-to-your-workstation

**Comment by seth** [comment]
I like these issues. I think it would be best to keep everything doc
related in the chef-docs-delivery repo. Mind moving these issues there?

**Comment by afiune** [comment]
Not at all.. I posted here because one customer is following it and he
pointed out that there is no instructions around it... I will switch him
over to the chef-docs-delivery :smile:

On Tuesday, August 18, 2015, Seth Falcon <notifications@github.com> wrote:

> I like these issues. I think it would be best to keep everything doc
> related in the chef-docs-delivery repo. Mind moving these issues there?
>
> On Mon, Aug 17, 2015 at 10:14 PM, Salim Afiune <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > For reference, the only place we say something about the pub key is at
> >
> https://github.com/chef/delivery_self_guided_trial/blob/master/workstation_setup.md#log-in-to-your-workstation
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/chef/delivery_self_guided_trial/issues/15#issuecomment-132073242
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/delivery_self_guided_trial/issues/15#issuecomment-132081867>
> .
>


-- 

*Salim Afiune* — Solutions Engineer

917.716.0448 – afiune@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/afiune>  Twitter <http://www.twitter.com/afiune>

CHEF

      CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by afiune** [comment]
Closing this issue since we will track it under chef-delivery-docs
